# Generated by Django 4.1.2 on 2022-11-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BatchProductionManagement', '0002_alter_machine_repair_duration'),
        ('BatchProductionManagement', '0002_remove_rawmaterial_last_updated_request_last_updated_and_more'),
    ]

    operations = [
    ]
