# Generated by Django 4.1.2 on 2022-11-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAndSalesManagement', '0003_alter_bulkorderrequest_province_and_more'),
        ('CustomerAndSalesManagement', '0003_alter_order_date_ordered'),
    ]

    operations = [
    ]
